language: node_js
node_js:
  - "8"
install:
  - npm install npm -g
  - npm config set audit false
  - npm ci
script:
  - npm run travis-ci
cache:
  directories:
    - node_modules
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
